Revert testing setup

diff --git a/.github/workflows/publish-android.yml b/.github/workflows/publish-android.yml
--- a/.github/workflows/publish-android.yml
+++ b/.github/workflows/publish-android.yml
@@ -27,45 +27,45 @@ jobs:
   build-package:
     runs-on: ubuntu-latest
     steps:
-      # - name: Checkout breez-sdk repo
-      #   uses: actions/checkout@v3
-      #   with:
-      #     ref: ${{ inputs.ref || github.sha }}
+      - name: Checkout breez-sdk repo
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ inputs.ref || github.sha }}
 
-      # - uses: actions/download-artifact@v3
-      #   with:
-      #     name: sdk-bindings-android-jniLibs
-      #     path: libs/sdk-bindings/bindings-android/lib/src/main/jniLibs
+      - uses: actions/download-artifact@v3
+        with:
+          name: sdk-bindings-android-jniLibs
+          path: libs/sdk-bindings/bindings-android/lib/src/main/jniLibs
 
-      # - uses: actions/download-artifact@v3
-      #   with:
-      #     name: bindings-kotlin
-      #     path: libs/sdk-bindings/bindings-android/lib/src/main/kotlin
+      - uses: actions/download-artifact@v3
+        with:
+          name: bindings-kotlin
+          path: libs/sdk-bindings/bindings-android/lib/src/main/kotlin
 
-      # - name: Build Android project
-      #   working-directory: libs/sdk-bindings/bindings-android
-      #   env:
-      #     ORG_GRADLE_PROJECT_libraryVersion: ${{ inputs.package-version || '0.0.1' }}
-      #   run: ./gradlew assemble
+      - name: Build Android project
+        working-directory: libs/sdk-bindings/bindings-android
+        env:
+          ORG_GRADLE_PROJECT_libraryVersion: ${{ inputs.package-version || '0.0.1' }}
+        run: ./gradlew assemble
 
-      # - name: Archive aar
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: android-release.aar
-      #     path: libs/sdk-bindings/bindings-android/lib/build/outputs/aar/lib-release.aar
+      - name: Archive aar
+        uses: actions/upload-artifact@v3
+        with:
+          name: android-release.aar
+          path: libs/sdk-bindings/bindings-android/lib/build/outputs/aar/lib-release.aar
         
-      # - name: Publish artifacts
-      #   if: ${{ inputs.publish }}
-      #   working-directory: libs/sdk-bindings/bindings-android
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #     BREEZ_MVN_USERNAME: ${{ secrets.BREEZ_MVN_USERNAME }}
-      #     BREEZ_MVN_PASSWORD: ${{ secrets.BREEZ_MVN_PASSWORD }}
-      #   run: |
-      #     ./gradlew publish -PlibraryVersion=${{ inputs.package-version }} -PbreezReposiliteUsername="$BREEZ_MVN_USERNAME" -PbreezReposilitePassword="$BREEZ_MVN_PASSWORD"
+      - name: Publish artifacts
+        if: ${{ inputs.publish }}
+        working-directory: libs/sdk-bindings/bindings-android
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BREEZ_MVN_USERNAME: ${{ secrets.BREEZ_MVN_USERNAME }}
+          BREEZ_MVN_PASSWORD: ${{ secrets.BREEZ_MVN_PASSWORD }}
+        run: |
+          ./gradlew publish -PlibraryVersion=${{ inputs.package-version }} -PbreezReposiliteUsername="$BREEZ_MVN_USERNAME" -PbreezReposilitePassword="$BREEZ_MVN_PASSWORD"
 
       - name: Trigger Jitpack build
-        # if: ${{ inputs.publish }}
+        if: ${{ inputs.publish }}
         shell: bash
         run: |
           # Jitpack only makes artifacts avaiable when someone requests them.
@@ -74,7 +74,7 @@ jobs:
           # We're waiting for at most 60s before triggering the Jitpack build to give our Maven repo
           # some time to process the just uploaded files (the Jitpack build is dependent upon them being available).
           # If anything fails here, we'll still finish sucessfully as this is an optional optimization.
-          timeout 10 bash -c 'while [[ "$(curl --output /dev/null --silent --head --write-out ''%{http_code}'' https://mvn.breez.technology/releases/breez_sdk/bindings-android/${{ inputs.package-version }}/bindings-android-${{ inputs.package-version }}.pom)" != "200" ]]; do echo "Waiting for package to be published on mvn.breez.technology..." && sleep 5; done && echo "Package found."' || echo "Package not found." && true
+          timeout 60 bash -c 'while [[ "$(curl --output /dev/null --silent --head --write-out ''%{http_code}'' https://mvn.breez.technology/releases/breez_sdk/bindings-android/${{ inputs.package-version }}/bindings-android-${{ inputs.package-version }}.pom)" != "200" ]]; do echo "Waiting for package to be published on mvn.breez.technology..." && sleep 5; done && echo "Package found."' || echo "Package not found." && true
           echo "Attempting to trigger Jitpack build..."
           curl -s -m 30 https://jitpack.io/api/builds/com.github.breez/breez-sdk/${{ inputs.package-version }} || true
           echo "Done"
